### ISSUE TITLE
The problem about train

### ISSUE THREAD

**Issue by Xxxia96** [weiyx15/DHGNN#17]
Hi, I want to ask about that when I try to run train.py, something is wrong. It shows the 'G has no attribute adjacency_list()'in the cora.py. Can you give me some advice for this

**Comment by weiyx15** [comment]
Hi~According to your feedback, the problem seems to be the version of `networkx` package. As is illustrated in `README.md`, please make sure your `networkx` version equals `1.11`, since we only test our code under `networkx==1.11`. Hope this reply could help you.
Best Regards.
