### ISSUE TITLE
The problem about DHGNN on citation network

### ISSUE THREAD

**Issue by dwang55** [weiyx15/DHGNN#21]
The paper claims that it can jointly learn embeddings from given graph structure and a hypergraph structure from feature space. I am confused about this process since the paper did not clearly explain this.

**Comment by weiyx15** [comment]
Hi~Thank you for your question!
In this paper, for the datasets with raw graph structures, like Cora, we would construct hyperedge set from both the raw graph structure (see method `DHGLayer._structure_select` in `DHGNN/models/layers.py`) and the feature embeddings (see methods `DHGLayer._nearest_select` and `DHGLayer._cluster_select` in `DHGNN/models/layers.py`). In this way, we are able to "jointly learning embeddings from given graph structure and a hypergraph structure from feature space".
