### ISSUE TITLE
新的特征嵌入和超图进化的问题

### ISSUE THREAD

**Issue by ChasionNo1** [weiyx15/DHGNN#28]
感谢你们团队出色的工作，在看完论文和代码后我有几个疑惑，希望可以得到解答。
1、图2所示是一个DHGNN流程，最后得到新的特征嵌入和原始特征维度相同，那么是如何确保这些特征是正确的。如何训练的。
2、如果按照代码里进行分类任务，是如何体现超图进化的思想。

**Comment by weiyx15** [comment]
您好！非常感谢您对该工作的关注，针对您的疑问，我们的回复如下：
1. DHGNN每层得到新特征嵌入的维度和卷积层变换矩阵的维度相关，新的特征嵌入与原始特征维度未必相同。
2. 超图进化的思想体现在，每个DHGNN层会根据当前的特征分布动态调整超图结构，体现了超图结构的变化。
希望以上回复能够帮到您！

**Comment by ChasionNo1** [comment]
感谢您的答疑，超图进化的思想是体现在多层DHGNN网络上的，假设有两层，第一层得到新的特征嵌入，然后第二层可以在新的特征基础上构建超图，然后最后也可以是分类任务，这样理解对吗？

**Comment by weiyx15** [comment]
是的，超图进化的思想体现在多层DHGNN网络中，后一层的网络基于前一层的特征上构建新的超图。与最后的任务关系不大，文章里是以节点分类任务为例说明的

**Comment by ChasionNo1** [comment]
好的，非常感谢您的解答！
