### ISSUE TITLE
您好，非常感谢您的工作，我想请教一个关于代码的问题

### ISSUE THREAD

**Issue by 1075793472** [weiyx15/DHGNN#31]
请问utils/construct_hypergraph  中的    construct_edge_list_from_cluster这个函数为什么一直没有调用到？如果不调用怎么从聚类结果中构造新的超边呢？

**Comment by weiyx15** [comment]
您好，DHGNN在代码中是通过`models/layers.py`中`DHGLayer`类的`_cluster_select`方法构造聚类形成超边的
