### ISSUE TITLE
关于 _structure_select 的问题

### ISSUE THREAD

**Issue by OuyKai** [weiyx15/DHGNN#34]
您好，请问 _structure_select 的意义是利用初始的构图信息吗，模型会同时利用生成的新超图和初始的旧超图？
完整的 hyperedge set 是不是包括
1、使用 K-means 生成的 n_cluster 个簇中离节点 u 最近的 n_center 个簇形成的 n_center(也即论文中的S-1) 超边
2、以节点 u 为中心使用k-nn 算法生成的一个超边
3、使用原始构图信息(edge_dict)选出 k_structured 个和节点 u 邻接的节点组成的另一个超边
所以完整的 hyperedge set 其实包括 S+1 个超边？

**Comment by zyl24** [comment]
您好，请问您解决了这个问题了吗？

**Comment by weiyx15** [comment]
您好，感谢您对我们工作的关注！
关于您的第一个问题，_structure_select是通过固有的图结构构造超图，在训练过程中模型会同时利用生成的新超图和初始的旧超图；
关于您的第二个问题，您的理解完全正确。在存在固有图结构的数据集中，对于每个节点u来说，u所关联的超边包括(1) n_center个质心离u最近的k-Means超边；(2) 一个以u为中心的knn超边；(3) 一个固有图结构k_structured个近邻节点和u构成的超边，所以一个节点关联的超边数量是S+1。
